### ISSUE TITLE
Hover?

### ISSUE THREAD

**Issue by christianmagill** [racha/tailwind-child#1]
I'm not sure if this is beyond the scope of this plugin, but if I want to target the hover state of a child item, the hover state get's activated on the parent instead.

For instance with the class "child-a:hover:underline" all links are underlined when the parent is hovered.

**Comment by racha** [comment]
Due to tailwind core and the way its parsing the class variants you have to do it in reverse...

here is an example

https://play.tailwindcss.com/u5XRKYcL36

In your case if you want a :hover on your child el you need to do `hover:child-a:underline`

**Comment by christianmagill** [comment]
Much thanks

Christian Magill
